import { Item, Update, Event, Message, DataSource, SyncLog } from './types'

export const mockItems: Item[] = [
  {
    id: '1',
    title: '完成PRD初稿评审',
    description: '与产品需求文档初稿需要在周五前完成评审并同步给设计团队',
    status: 'in-progress',
    priority: 'high',
    deadline: '2026-05-30',
    source: '周会纪要',
    assignee: '我',
    latestProgress: '已完成80%，需要补充技术方案部分',
    createdAt: '2026-05-26',
    updatedAt: '2026-05-27',
  },
  {
    id: '2',
    title: '跟进设计稿反馈',
    description: '设计团队已提交第一版设计稿，需要在明天给出反馈意见',
    status: 'pending',
    priority: 'high',
    deadline: '2026-05-29',
    source: '群聊',
    assignee: '我',
    latestProgress: '设计稿已收到，待查看',
    createdAt: '2026-05-27',
    updatedAt: '2026-05-27',
  },
  {
    id: '3',
    title: '技术方案评审准备',
    description: '下周三进行技术方案评审，需要提前准备材料',
    status: 'pending',
    priority: 'medium',
    deadline: '2026-06-03',
    source: '文档',
    assignee: '我',
    latestProgress: '尚未开始',
    createdAt: '2026-05-25',
    updatedAt: '2026-05-25',
  },
  {
    id: '4',
    title: '用户调研总结',
    description: '整理上周用户访谈的反馈，形成总结报告',
    status: 'completed',
    priority: 'medium',
    source: '会议纪要',
    assignee: '我',
    latestProgress: '已完成并发送给团队',
    createdAt: '2026-05-20',
    updatedAt: '2026-05-26',
  },
  {
    id: '5',
    title: '修复生产环境性能问题',
    description: '生产环境出现偶发性的性能问题，需要紧急修复',
    status: 'in-progress',
    priority: 'high',
    deadline: '2026-05-28',
    source: '告警',
    assignee: '我',
    latestProgress: '已定位问题根源，正在修复',
    risks: '如果不及时修复，可能影响用户体验',
    createdAt: '2026-05-28',
    updatedAt: '2026-05-28',
  },
  {
    id: '6',
    title: '更新API文档',
    description: 'API接口有变更，需要更新对应的文档',
    status: 'on-hold',
    priority: 'low',
    source: '群聊',
    assignee: '我',
    latestProgress: '等待开发完成后更新',
    createdAt: '2026-05-24',
    updatedAt: '2026-05-24',
  },
  {
    id: '7',
    title: '代码审查',
    description: '审查团队成员提交的代码',
    status: 'confirm',
    priority: 'medium',
    deadline: '2026-05-29',
    source: 'GitHub',
    assignee: '我',
    latestProgress: '已审查完成，等待确认',
    createdAt: '2026-05-27',
    updatedAt: '2026-05-28',
  },
]

export const mockUpdates: Update[] = [
  {
    id: '1',
    sourceType: 'document',
    time: '2026-05-28',
    summary: '产品规划文档更新：Q2核心产品方向已锁定个人AI智能操作系统，产品定位为个人AI助手 + 进度追踪 + 信息聚合 + 团队协作，MVP功能范围已完全确定',
    importance: 'high',
    affectedObjects: ['进度罗盘', '产品规划', 'MVP范围'],
    suggestedAction: '立即同步给开发团队',
    sourceLink: 'https://bytedance.larkoffice.com/wiki/KLQEw5N2qih3tKkX2OUc66Hbn2f',
    title: '产品规划文档重大更新',
    status: 'on-track',
    pocStatus: 'verified',
    lastUpdate: '5分钟前',
    assignee: '李开心',
    progress: 75,
    milestones: ['核心功能确认', 'MVP范围锁定', '5年战略规划'],
    metrics: [
      { label: '核心模块', value: '5个', trend: 'stable' },
      { label: '用户覆盖', value: '预计10万+', trend: 'up' },
      { label: 'MAU目标', value: 'Q2达成3万', trend: 'up' },
      { label: '转化漏斗', value: '62%', trend: 'stable' }
    ],
    relatedModules: ['首页', 'AI助手', '事项管理', '团队动态', '大事记'],
    docName: '产品规划文档'
  },
  {
    id: '1-1',
    sourceType: 'document',
    time: '2026-05-28',
    summary: '产品规划文档新增：首页设计已完成从传统列表到智能工作台的升级，新增Hero区域、视觉卡片、今日重点、新增变化、今日建议等模块',
    importance: 'high',
    affectedObjects: ['首页设计', '产品规划'],
    suggestedAction: '确认首页UI方案',
    sourceLink: 'https://bytedance.larkoffice.com/wiki/KLQEw5N2qih3tKkX2OUc66Hbn2f',
    title: '首页设计方案确认',
    status: 'new',
    pocStatus: 'in-progress',
    lastUpdate: '30分钟前',
    assignee: '产品团队',
    progress: 80,
    milestones: ['需求调研', '原型设计', '方案确认'],
    metrics: [
      { label: '卡片类型', value: '5种', trend: 'up' },
      { label: '设计规范', value: '已同步', trend: 'stable' }
    ],
    relatedModules: ['首页', 'Hero区域', '概览卡片', '今日重点'],
    docName: '产品规划文档'
  },
  {
    id: '2',
    sourceType: 'document',
    time: '2026-05-27',
    summary: '设计规范文档更新：设计系统v2.0已发布，包含全新的Maillard风格配色、圆角系统、间距规范，新增60+新组件，完整的移动端适配已完成',
    importance: 'high',
    affectedObjects: ['设计规范', 'UI/UX'],
    suggestedAction: '本周组织设计评审',
    sourceLink: 'https://bytedance.larkoffice.com/wiki/Hejow2oznizKpqk61pOcac4Rnpl',
    title: '设计系统v2.0发布',
    status: 'new',
    pocStatus: 'in-progress',
    lastUpdate: '2小时前',
    assignee: '设计团队',
    progress: 100,
    milestones: ['色彩系统确定', '组件库设计', '设计规范发布'],
    metrics: [
      { label: '组件覆盖率', value: '92%', trend: 'up' },
      { label: '设计效率', value: '提升2.3x', trend: 'up' },
      { label: '新组件', value: '60+个', trend: 'up' }
    ],
    relatedModules: ['工作台', '卡片设计', '导航系统', '色彩规范'],
    docName: '设计规范文档'
  },
  {
    id: '2-1',
    sourceType: 'document',
    time: '2026-05-27',
    summary: '设计规范文档新增Maillard配色系统：包含主色#5B6CFF、背景#F7F8FC、卡片#FFFFFF、次级#6B7280等规范，统一圆角系统为rounded-3xl',
    importance: 'high',
    affectedObjects: ['色彩规范', 'UI组件'],
    suggestedAction: '应用新配色到所有页面',
    sourceLink: 'https://bytedance.larkoffice.com/wiki/Hejow2oznizKpqk61pOcac4Rnpl',
    title: 'Maillard配色方案确认',
    status: 'new',
    pocStatus: 'verified',
    lastUpdate: '1小时前',
    assignee: '设计团队',
    progress: 90,
    milestones: ['色彩调研', '方案确认', '应用推广'],
    metrics: [
      { label: '主色方案', value: '#5B6CFF', trend: 'stable' },
      { label: '背景色', value: '#F7F8FC', trend: 'stable' }
    ],
    relatedModules: ['色彩规范', 'UI组件'],
    docName: '设计规范文档'
  },
  {
    id: '3',
    sourceType: 'meeting',
    time: '2026-05-27',
    summary: '周会确定了进度罗盘优先级，PRD评审时间锁定本周五，需要提前准备技术方案',
    importance: 'high',
    affectedObjects: ['进度罗盘'],
    suggestedAction: '跟进PRD评审准备',
    sourceLink: 'https://feishu.cn/doc/meeting-notes',
    title: 'PRD评审倒计时3天',
    status: 'at-risk',
    pocStatus: 'planned',
    lastUpdate: '1天前',
    assignee: '李开心',
    progress: 40,
    milestones: ['原型完成', '方案评审', '开发排期'],
    metrics: [
      { label: '剩余时间', value: '3天', trend: 'down' },
      { label: '完成度', value: '40%', trend: 'up' }
    ],
    relatedModules: ['PRD', '项目排期'],
    docName: '周会纪要'
  },
  {
    id: '4',
    sourceType: 'document',
    time: '2026-05-26',
    summary: '技术架构文档已更新：推荐React18.2.0 + TypeScript + Vite5.1.3技术栈，包含完整项目模板、Tailwind CSS3.4.1配置、Lucide图标库、React Router6.22.0路由方案',
    importance: 'high',
    affectedObjects: ['技术架构', '新功能迭代'],
    suggestedAction: '参考模板搭建项目框架',
    sourceLink: 'https://bytedance.larkoffice.com/wiki/ZJHMw0iBIiL2xJkaUEgck8Afn6d',
    title: '技术架构更新完成',
    status: 'completed',
    pocStatus: 'verified',
    lastUpdate: '3天前',
    assignee: '架构团队',
    progress: 100,
    milestones: ['技术选型', '架构设计', '文档发布'],
    metrics: [
      { label: '构建速度', value: '提升65%', trend: 'up' },
      { label: '代码规范', value: 'ESLint全覆盖', trend: 'up' },
      { label: '热更新', value: '<500ms', trend: 'up' }
    ],
    relatedModules: ['开发环境', 'CI/CD', '代码质量'],
    docName: '技术架构文档'
  },
  {
    id: '4-1',
    sourceType: 'document',
    time: '2026-05-26',
    summary: '技术架构文档新增状态管理方案：使用React useState + Context API，包含ItemsContext和UserContext两个核心上下文，类型安全的TypeScript实现',
    importance: 'high',
    affectedObjects: ['状态管理', '架构规范'],
    suggestedAction: '团队学习状态管理模式',
    sourceLink: 'https://bytedance.larkoffice.com/wiki/ZJHMw0iBIiL2xJkaUEgck8Afn6d',
    title: '状态管理方案确认',
    status: 'new',
    pocStatus: 'verified',
    lastUpdate: '2天前',
    assignee: '架构团队',
    progress: 100,
    milestones: ['方案调研', '代码编写', '文档发布'],
    metrics: [
      { label: '类型安全', value: '100%', trend: 'stable' },
      { label: '上下文数量', value: '2个', trend: 'stable' }
    ],
    relatedModules: ['ItemsContext', 'UserContext'],
    docName: '技术架构文档'
  },
  {
    id: '5',
    sourceType: 'chat',
    time: '2026-05-26',
    summary: '设计稿第一版已出，包含完整的产品体验流程，正在收集反馈',
    importance: 'high',
    affectedObjects: ['进度罗盘'],
    suggestedAction: '今日内完成设计稿反馈',
    sourceLink: 'https://feishu.cn/chat',
    title: '第一版设计稿出炉',
    status: 'on-track',
    pocStatus: 'in-progress',
    lastUpdate: '3天前',
    assignee: '设计团队',
    progress: 55,
    milestones: ['设计稿v1', '反馈收集', '设计稿v2'],
    metrics: [
      { label: '页面数', value: '28页', trend: 'stable' },
      { label: '交互状态', value: '36个', trend: 'stable' }
    ],
    relatedModules: ['首页', '事项管理', 'AI助手', '大事记'],
    docName: '群聊'
  },
  {
    id: '6',
    sourceType: 'document',
    time: '2026-05-25',
    summary: '产品里程碑更新：6月完成UI设计、7月完成开发、8月测试上线，Q2完成率目标90%+',
    importance: 'medium',
    affectedObjects: ['项目计划', '进度罗盘'],
    suggestedAction: '同步更新项目里程碑',
    sourceLink: 'https://bytedance.larkoffice.com/wiki/KLQEw5N2qih3tKkX2OUc66Hbn2f',
    title: 'Q2里程碑更新',
    status: 'on-track',
    pocStatus: 'planned',
    lastUpdate: '4天前',
    assignee: '产品团队',
    progress: 65,
    milestones: ['5月PRD', '6月UI', '7月开发', '8月上线'],
    metrics: [
      { label: 'Q2完成率', value: '当前72%', trend: 'up' },
      { label: '剩余工时', value: '18人天', trend: 'down' }
    ],
    relatedModules: ['项目管理', '进度追踪'],
    docName: '产品规划文档'
  },
  {
    id: '7',
    sourceType: 'document',
    time: '2026-05-25',
    summary: '团队周报显示Q2完成率85%，好于预期，AI相关功能完成度91%',
    importance: 'medium',
    affectedObjects: ['团队整体'],
    sourceLink: 'https://feishu.cn/doc/team-report',
    title: 'Q2团队周报发布',
    status: 'on-track',
    pocStatus: 'verified',
    lastUpdate: '4天前',
    assignee: '全体成员',
    progress: 85,
    milestones: ['Q2目标回顾', 'Q3规划'],
    metrics: [
      { label: '团队士气', value: '优秀', trend: 'up' },
      { label: '交付准时率', value: '94%', trend: 'up' },
      { label: '迭代速度', value: '2周/迭代', trend: 'stable' }
    ],
    relatedModules: ['团队管理'],
    docName: '团队周报'
  },
  {
    id: '8',
    sourceType: 'document',
    time: '2026-05-24',
    summary: '交互指南更新：包含15种新动效、状态设计、和无障碍规范，覆盖全部核心场景',
    importance: 'medium',
    affectedObjects: ['设计规范', '交互设计'],
    suggestedAction: '组织设计师学习',
    sourceLink: 'https://bytedance.larkoffice.com/wiki/Hejow2oznizKpqk61pOcac4Rnpl',
    title: '交互指南v2.0发布',
    status: 'completed',
    pocStatus: 'verified',
    lastUpdate: '5天前',
    assignee: '设计团队',
    progress: 100,
    milestones: ['动效设计', '状态规范', '无障碍指南'],
    metrics: [
      { label: '动效数量', value: '15+', trend: 'up' },
      { label: '覆盖率', value: '95%', trend: 'up' }
    ],
    relatedModules: ['交互系统'],
    docName: '设计规范文档'
  },
  {
    id: '9',
    sourceType: 'external',
    time: '2026-05-24',
    summary: '激励政策更新发布，包含新的奖励机制和晋升标准',
    importance: 'low',
    affectedObjects: ['全体成员'],
    sourceLink: 'https://feishu.cn/doc/incentive-report',
    title: '激励政策更新',
    status: 'on-track',
    pocStatus: 'planned',
    lastUpdate: '5天前',
    assignee: 'HR团队',
    progress: 80,
    milestones: ['政策调研', '方案制定', '发布通知'],
    metrics: [
      { label: '激励覆盖率', value: '全员', trend: 'stable' }
    ],
    relatedModules: ['员工激励'],
    docName: '激励政策文档'
  },
  {
    id: '10',
    sourceType: 'document',
    time: '2026-05-23',
    summary: 'CI/CD配置已完成，包含自动化构建、测试、部署完整流程，配置代码已开源',
    importance: 'medium',
    affectedObjects: ['技术架构', 'DevOps'],
    suggestedAction: '配置项目流水线',
    sourceLink: 'https://bytedance.larkoffice.com/wiki/ZJHMw0iBIiL2xJkaUEgck8Afn6d',
    title: 'CI/CD流水线搭建完成',
    status: 'completed',
    pocStatus: 'verified',
    lastUpdate: '6天前',
    assignee: 'DevOps团队',
    progress: 100,
    milestones: ['配置设计', '搭建环境', '自动化部署'],
    metrics: [
      { label: '部署频率', value: '每小时', trend: 'up' },
      { label: '回滚时间', value: '5分钟', trend: 'down' },
      { label: '自动化测试', value: '覆盖率85%', trend: 'up' }
    ],
    relatedModules: ['CI/CD系统'],
    docName: '技术架构文档'
  },
  {
    id: '11',
    sourceType: 'document',
    time: '2026-05-22',
    summary: '市场分析完成，目标用户锁定白领和知识工作者，用户画像已生成',
    importance: 'medium',
    affectedObjects: ['用户研究', '市场分析'],
    suggestedAction: '完成用户调研问卷',
    sourceLink: 'https://bytedance.larkoffice.com/wiki/KLQEw5N2qih3tKkX2OUc66Hbn2f',
    title: '目标用户画像完成',
    status: 'on-track',
    pocStatus: 'verified',
    lastUpdate: '7天前',
    assignee: '用研团队',
    progress: 90,
    milestones: ['用户访谈', '画像分析', '调研问卷'],
    metrics: [
      { label: '访谈人数', value: '50+', trend: 'up' },
      { label: '问卷反馈', value: '300+', trend: 'up' }
    ],
    relatedModules: ['用户调研'],
    docName: '产品规划文档'
  },
  {
    id: '12',
    sourceType: 'document',
    time: '2026-05-21',
    summary: '无障碍设计指南已发布，包含WCAG 2.1 AA标准、键盘导航、屏幕阅读器支持等完整内容',
    importance: 'low',
    affectedObjects: ['设计规范', '无障碍设计'],
    sourceLink: 'https://bytedance.larkoffice.com/wiki/Hejow2oznizKpqk61pOcac4Rnpl',
    title: '无障碍设计规范发布',
    status: 'completed',
    pocStatus: 'verified',
    lastUpdate: '8天前',
    assignee: '设计团队',
    progress: 100,
    milestones: ['规范制定', '指南发布'],
    relatedModules: ['设计规范'],
    docName: '设计规范文档'
  },
]

export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'OpenAI发布GPT-5，多模态与复杂任务推理能力进一步增强',
    category: 'ai',
    time: '2026-05-28',
    summary: 'OpenAI发布了GPT-5模型，在多模态理解与复杂任务执行能力上进一步提升',
    sourceLink: 'https://36kr.com/p/123456789',
    source: '36氪',
    sources: ['OpenAI官方博客', '36氪', '极客公园'],
    impactAnalysis: '对AI应用层竞争格局产生重大影响',
    oneLineSummary: 'OpenAI正式发布GPT-5，多模态理解能力提升40%，上下文窗口扩展至100万token',
    aiComment: '该事件表明头部模型能力仍在快速迭代，AI应用层的竞争重点可能进一步转向场景整合、任务编排与体验差异化。',
    reasonForRecommendation: '直接关系到你负责的"进度罗盘"产品开发，与AI助手与个人情报能力方向高度相关',
    recommendationLevel: 'S',
    hotTags: ['GPT-5', 'OpenAI', '多模态AI', '技术突破'],
    suggestedFocus: ['是否开放API', '是否具备稳定商用条件', '成本是否适合高频场景', '是否会拉开与现有竞品的能力差距'],
    hotScore: 98,
    authoritativeScore: 95,
    influenceScore: 95,
    relevanceScore: 92,
    timelinessScore: 100,
    isFeatured: true,
    isHighHeat: true,
    isRelatedToMe: true,
    isFollowed: false,
  },
  {
    id: '2',
    title: '字节跳动发布新AI应用平台「智能工作台」',
    category: 'competitor',
    time: '2026-05-27',
    summary: '字节跳动发布了新的AI应用开发平台，主打低代码AI应用开发和个人信息聚合',
    sourceLink: 'https://huxiu.com/article/987654321',
    source: '虎嗅',
    sources: ['虎嗅', '36氪', '晚点LatePost'],
    impactAnalysis: '直接竞品信号，需要高度关注',
    oneLineSummary: '字节跳动发布"智能工作台"产品，主打低代码AI应用开发和个人信息聚合',
    aiComment: '这是一个直接的竞品信号，说明AI信息聚合产品正成为大厂的战略方向，我们需要重新审视产品定位。',
    reasonForRecommendation: '竞品动态，与你正在做的"进度罗盘"高度相关，可能影响市场格局',
    recommendationLevel: 'S',
    hotTags: ['字节跳动', '竞品分析', 'AI工作台', '战略布局'],
    suggestedFocus: ['对比分析其功能模块', '设计理念与用户体验', '商业化路径', '技术架构特点'],
    hotScore: 92,
    authoritativeScore: 90,
    influenceScore: 90,
    relevanceScore: 95,
    timelinessScore: 95,
    isFeatured: true,
    isHighHeat: true,
    isRelatedToMe: true,
    isFollowed: false,
  },
  {
    id: '3',
    title: '网信办发布《生成式AI服务管理规定》修订版',
    category: 'policy',
    time: '2026-05-26',
    summary: '国家出台了新的AI应用监管政策，明确个人AI助手的合规要求',
    sourceLink: 'https://geekpark.net/news/1357924680',
    source: '极客公园',
    sources: ['网信办官网', '极客公园', '财联社'],
    impactAnalysis: '对所有AI应用产生合规性影响',
    oneLineSummary: '网信办发布《生成式AI服务管理规定》修订版，明确个人AI助手的合规要求',
    aiComment: '合规门槛提高，但也让正规产品获得更好的竞争环境，需要调整隐私和安全方案。',
    reasonForRecommendation: '直接影响产品合规性，可能需要调整开发计划和功能设计',
    recommendationLevel: 'A',
    hotTags: ['政策监管', 'AI合规', '网信办', '数据安全'],
    suggestedFocus: ['数据采集要求', '用户隐私保护', '内容审核机制', '备案要求'],
    hotScore: 85,
    authoritativeScore: 100,
    influenceScore: 95,
    relevanceScore: 85,
    timelinessScore: 90,
    isFeatured: true,
    isHighHeat: true,
    isRelatedToMe: true,
    isFollowed: false,
  },
  {
    id: '4',
    title: 'AI Agent技术架构深度解析',
    category: 'tech',
    time: '2026-05-25',
    summary: '极客公园旗下内容号发布了深度AI技术分析报告',
    sourceLink: 'https://geekpark.net/post/246813579',
    source: '极客公园',
    sources: ['极客公园', '技术公众号'],
    impactAnalysis: '技术参考价值高',
    oneLineSummary: '极客公园深度解析AutoGPT-5技术架构，详细分析Agent工作流和记忆机制',
    aiComment: '这是一份技术含金量很高的报告，对我们的技术选型有直接参考价值。',
    reasonForRecommendation: '与你正在进行的技术方案设计高度相关，可直接借鉴',
    recommendationLevel: 'A',
    hotTags: ['AI Agent', '技术架构', 'AutoGPT', '深度技术'],
    suggestedFocus: ['记忆管理机制', '工具调用框架', '任务分解策略', '评估方法'],
    hotScore: 78,
    authoritativeScore: 85,
    influenceScore: 85,
    relevanceScore: 88,
    timelinessScore: 88,
    isFeatured: false,
    isHighHeat: false,
    isRelatedToMe: true,
    isFollowed: true,
  },
  {
    id: '5',
    title: '钛媒体：科技行业2026年中展望',
    category: 'tech',
    time: '2026-05-24',
    summary: '钛媒体发布了科技行业2026年中展望分析报告',
    sourceLink: 'https://tmtpost.com/article/567891234',
    source: '钛媒体',
    sources: ['钛媒体'],
    impactAnalysis: '行业趋势参考',
    oneLineSummary: '钛媒体发布年中展望：AI助手进入成熟期，个人知识管理成为新赛道',
    aiComment: '行业趋势验证了我们的产品方向，需要加速落地抢占市场先机。',
    reasonForRecommendation: '了解行业大盘，辅助产品决策',
    recommendationLevel: 'A',
    hotTags: ['行业趋势', '年中展望', '个人知识管理', '市场分析'],
    suggestedFocus: ['用户需求变化', '市场规模预测', '成功案例分析', '竞争格局'],
    hotScore: 72,
    authoritativeScore: 82,
    influenceScore: 80,
    relevanceScore: 75,
    timelinessScore: 85,
    isFeatured: false,
    isHighHeat: false,
    isRelatedToMe: false,
    isFollowed: false,
  },
  {
    id: '6',
    title: '3家AI信息聚合创业公司宣布完成A轮融资',
    category: 'tech',
    time: '2026-05-23',
    summary: 'Tech星球发布了最新的创业公司融资和产品动态',
    sourceLink: 'https://techplanet.com/article/987654321',
    source: 'Tech星球',
    sources: ['Tech星球', '36氪'],
    impactAnalysis: '赛道热度持续上升',
    oneLineSummary: '3家AI信息聚合创业公司宣布完成A轮融资，合计金额超5亿',
    aiComment: '赛道热度持续上升，资本正在加速布局，我们需要加快产品迭代。',
    reasonForRecommendation: '了解资本和市场对同类产品的态度',
    recommendationLevel: 'B',
    hotTags: ['融资动态', '创业公司', '资本市场', '竞品'],
    suggestedFocus: ['产品特点', '团队背景', '融资用途', '用户增长数据'],
    hotScore: 68,
    authoritativeScore: 75,
    influenceScore: 70,
    relevanceScore: 72,
    timelinessScore: 82,
    isFeatured: false,
    isHighHeat: false,
    isRelatedToMe: true,
    isFollowed: false,
  },
  {
    id: '7',
    title: '晚点LatePost万字长文：AI产业生态正在重构',
    category: 'ai',
    time: '2026-05-22',
    summary: '晚点LatePost发布了AI产业深度报道',
    sourceLink: 'https://latepost.com/p/1357924680',
    source: '晚点LatePost',
    sources: ['晚点LatePost'],
    impactAnalysis: '产业观察价值高',
    oneLineSummary: '晚点LatePost万字长文：从ChatGPT到个人AI，产业生态正在重构',
    aiComment: '这是一份全景式产业观察，对理解行业格局和找准产品定位很有帮助。',
    reasonForRecommendation: '深入了解AI产业生态的整体变化',
    recommendationLevel: 'B',
    hotTags: ['产业格局', '深度报道', '生态重构', '行业观察'],
    suggestedFocus: ['生态参与者', '商业模式演变', '技术路线图', '未来预测'],
    hotScore: 65,
    authoritativeScore: 88,
    influenceScore: 82,
    relevanceScore: 68,
    timelinessScore: 80,
    isFeatured: false,
    isHighHeat: false,
    isRelatedToMe: false,
    isFollowed: false,
  },
  {
    id: '8',
    title: '界面新闻专题：AI监管下的产品创新',
    category: 'tech',
    time: '2026-05-21',
    summary: '界面新闻科技频道发布专题报道，多家头部公司分享经验',
    sourceLink: 'https://jiemian.com/article/246813579',
    source: '界面新闻',
    sources: ['界面新闻'],
    impactAnalysis: '合规参考价值',
    oneLineSummary: '界面新闻专题：如何在合规框架内做AI产品创新？多家头部公司分享经验',
    aiComment: '合规与创新的平衡是当前AI产品的核心挑战，这些经验很有借鉴意义。',
    reasonForRecommendation: '学习行业先行者的合规实践',
    recommendationLevel: 'B',
    hotTags: ['合规创新', '最佳实践', '案例学习', '头部公司'],
    suggestedFocus: ['数据治理机制', '用户同意流程', '内容审核体系', '风险控制措施'],
    hotScore: 60,
    authoritativeScore: 80,
    influenceScore: 75,
    relevanceScore: 70,
    timelinessScore: 78,
    isFeatured: false,
    isHighHeat: false,
    isRelatedToMe: true,
    isFollowed: false,
  },
  {
    id: '9',
    title: '第一财经：2026年AI产品商业化加速',
    category: 'tech',
    time: '2026-05-20',
    summary: '第一财经科技频道发布行业分析报告',
    sourceLink: 'https://yicai.com/news/369124578',
    source: '第一财经',
    sources: ['第一财经'],
    impactAnalysis: '商业化趋势参考',
    oneLineSummary: '第一财经分析：2026年AI产品商业化加速，订阅制成为主流模式',
    aiComment: '商业化路径逐渐清晰，这对我们未来的产品规划有参考价值。',
    reasonForRecommendation: '了解行业商业化趋势和变现模式',
    recommendationLevel: 'B',
    hotTags: ['商业化', '订阅制', '财务分析', '变现模式'],
    suggestedFocus: ['付费转化率', '用户生命周期价值', '成本结构', '定价策略'],
    hotScore: 55,
    authoritativeScore: 78,
    influenceScore: 70,
    relevanceScore: 58,
    timelinessScore: 75,
    isFeatured: false,
    isHighHeat: false,
    isRelatedToMe: false,
    isFollowed: false,
  },
  {
    id: '10',
    title: '财联社：AI芯片供应链持续紧张',
    category: 'tech',
    time: '2026-05-19',
    summary: '财联社TMT科技频道发布最新行业快讯',
    sourceLink: 'https://cls.cn/kuaixun/1593574862',
    source: '财联社',
    sources: ['财联社'],
    impactAnalysis: '基础设施影响',
    oneLineSummary: '财联社快讯：AI芯片供应链持续紧张，英伟达H200价格再涨15%',
    aiComment: '芯片成本上升可能会影响AI服务的定价，但对我们的SaaS产品影响较小。',
    reasonForRecommendation: '了解基础设施层面的变化',
    recommendationLevel: 'B',
    hotTags: ['AI芯片', '供应链', '英伟达', '硬件成本'],
    suggestedFocus: ['价格走势', '替代方案', '长期影响评估'],
    hotScore: 52,
    authoritativeScore: 75,
    influenceScore: 65,
    relevanceScore: 45,
    timelinessScore: 72,
    isFeatured: false,
    isHighHeat: false,
    isRelatedToMe: false,
    isFollowed: false,
  },
  {
    id: '11',
    title: '新浪科技：IBM宣布量子计算新突破',
    category: 'ai',
    time: '2026-05-18',
    summary: '新浪科技报道最新前沿技术进展',
    sourceLink: 'https://tech.sina.com.cn/i/246813579',
    source: '新浪科技',
    sources: ['新浪科技'],
    impactAnalysis: '长期技术趋势',
    oneLineSummary: 'IBM宣布量子计算新突破，量子体积提升至100万',
    aiComment: '这是长期趋势，短期内不会影响我们的产品开发。',
    reasonForRecommendation: '保持对前沿技术的了解',
    recommendationLevel: 'B',
    hotTags: ['量子计算', '前沿技术', 'IBM', '技术突破'],
    suggestedFocus: ['了解趋势即可'],
    hotScore: 48,
    authoritativeScore: 72,
    influenceScore: 60,
    relevanceScore: 35,
    timelinessScore: 70,
    isFeatured: false,
    isHighHeat: false,
    isRelatedToMe: false,
    isFollowed: false,
  },
  {
    id: '12',
    title: '网易科技：云计算厂商开打价格战',
    category: 'tech',
    time: '2026-05-17',
    summary: '网易科技发布科技行业深度专题',
    sourceLink: 'https://tech.163.com/tech/1593574862',
    source: '网易科技',
    sources: ['网易科技'],
    impactAnalysis: '成本优化机会',
    oneLineSummary: '网易科技：云计算厂商开打价格战，云服务价格平均下降20%',
    aiComment: '云服务成本下降对我们是利好，可以降低运营成本。',
    reasonForRecommendation: '了解基础设施成本变化',
    recommendationLevel: 'B',
    hotTags: ['云计算', '价格战', '成本优化', '云服务'],
    suggestedFocus: ['各家厂商降价策略', '迁移时机评估'],
    hotScore: 45,
    authoritativeScore: 70,
    influenceScore: 55,
    relevanceScore: 40,
    timelinessScore: 68,
    isFeatured: false,
    isHighHeat: false,
    isRelatedToMe: false,
    isFollowed: false,
  },
  {
    id: '13',
    title: '腾讯科技专访：元宇宙发展重心转向企业应用',
    category: 'tech',
    time: '2026-05-16',
    summary: '腾讯科技发布行业领袖独家专访',
    sourceLink: 'https://tech.qq.com/a/246813579',
    source: '腾讯科技',
    sources: ['腾讯科技'],
    impactAnalysis: '趋势观察',
    oneLineSummary: '腾讯科技专访Meta CTO：元宇宙发展重心转向企业应用',
    aiComment: '元宇宙概念有所降温，重心转向实用场景，当前与我们产品方向关联不大。',
    reasonForRecommendation: '了解行业前沿动态',
    recommendationLevel: 'B',
    hotTags: ['元宇宙', 'Meta', '企业应用', '趋势变化'],
    suggestedFocus: ['了解即可'],
    hotScore: 40,
    authoritativeScore: 68,
    influenceScore: 50,
    relevanceScore: 30,
    timelinessScore: 65,
    isFeatured: false,
    isHighHeat: false,
    isRelatedToMe: false,
    isFollowed: false,
  },
]

export const mockMessages: Message[] = [
  {
    id: '1',
    role: 'assistant',
    content: '你好！我是你的AI助手。我可以帮你：\n\n1. 查看最近跟进的事项\n2. 了解项目进展\n3. 查看团队动态\n4. 了解行业大事\n5. 生成周报或汇报材料\n\n有什么需要帮助的吗？',
    timestamp: '2026-05-28 09:00',
  },
]

export const mockDataSources: DataSource[] = [
  {
    id: '1',
    name: '进度罗盘产品规划文档',
    link: 'https://bytedance.larkoffice.com/wiki/KLQEw5N2qih3tKkX2OUc66Hbn2f',
    type: 'wiki',
    module: 'team',
    topic: '进度罗盘',
    frequency: 'daily',
    status: 'enabled',
    remark: '主要用于提取产品规划和项目进展',
    lastSyncTime: '2026-05-28 08:30',
    lastSyncStatus: 'success',
    lastSyncResult: '成功提取了5条记录',
    createdAt: '2026-05-20',
    updatedAt: '2026-05-28',
  },
  {
    id: '2',
    name: '设计规范文档',
    link: 'https://bytedance.larkoffice.com/wiki/Hejow2oznizKpqk61pOcac4Rnpl',
    type: 'wiki',
    module: 'team',
    topic: '设计系统',
    frequency: 'weekly',
    status: 'enabled',
    remark: '设计规范和设计系统更新',
    lastSyncTime: '2026-05-25 14:00',
    lastSyncStatus: 'success',
    lastSyncResult: '成功提取了3条记录',
    createdAt: '2026-05-15',
    updatedAt: '2026-05-25',
  },
  {
    id: '3',
    name: '技术架构文档',
    link: 'https://bytedance.larkoffice.com/wiki/ZJHMw0iBIiL2xJkaUEgck8Afn6d',
    type: 'wiki',
    module: 'team',
    topic: '技术架构',
    frequency: 'manual',
    status: 'enabled',
    remark: '技术架构和实现细节',
    lastSyncTime: '2026-05-20 10:00',
    lastSyncStatus: 'success',
    lastSyncResult: '成功提取了4条记录',
    createdAt: '2026-05-10',
    updatedAt: '2026-05-20',
  },
  {
    id: '4',
    name: '激励方向大周会-26年Q2',
    link: 'https://feishu.cn/doc/meeting-notes',
    type: 'doc',
    module: 'team',
    topic: '团队周会',
    frequency: 'weekly',
    status: 'enabled',
    remark: '每周团队会议纪要',
    lastSyncTime: '2026-05-27 18:00',
    lastSyncStatus: 'failed',
    lastSyncResult: '同步失败：文档权限不足',
    createdAt: '2026-04-01',
    updatedAt: '2026-05-27',
  },
  {
    id: '5',
    name: '产品PRD评审文档',
    link: 'https://feishu.cn/doc/prd-v1',
    type: 'docx',
    module: 'team',
    topic: '产品PRD',
    frequency: 'manual',
    status: 'disabled',
    remark: '产品PRD文档，已暂停同步',
    lastSyncTime: '2026-05-18 16:00',
    lastSyncStatus: 'success',
    lastSyncResult: '成功提取了2条记录',
    createdAt: '2026-05-01',
    updatedAt: '2026-05-22',
  },
]

export const mockSyncLogs: SyncLog[] = [
  {
    id: '1',
    dataSourceId: '1',
    startTime: '2026-05-28 08:25:30',
    endTime: '2026-05-28 08:30:00',
    status: 'success',
    hasChanges: true,
    snapshotVersion: 'v1.0.5',
    parsedRecords: 5,
  },
  {
    id: '2',
    dataSourceId: '1',
    startTime: '2026-05-27 08:25:00',
    endTime: '2026-05-27 08:28:30',
    status: 'success',
    hasChanges: false,
    snapshotVersion: 'v1.0.4',
    parsedRecords: 0,
  },
  {
    id: '3',
    dataSourceId: '4',
    startTime: '2026-05-27 17:55:00',
    endTime: '2026-05-27 18:00:00',
    status: 'failed',
    hasChanges: false,
    snapshotVersion: 'v1.0.2',
    parsedRecords: 0,
    errorMessage: '同步失败：文档权限不足',
  },
]
